"""table creation

Revision ID: 155af3a385ed
Revises: 
Create Date: 2022-10-23 17:40:01.579260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155af3a385ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id_author', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('surname', sa.String(length=32), nullable=True),
    sa.Column('patronymic', sa.String(length=32), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id_author')
    )
    op.create_table('client',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id_client')
    )
    op.create_table('book',
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('id_author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['author.id_author'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_book')
    )
    op.create_table('cart',
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cart')
    )
    op.create_table('purchase',
    sa.Column('id_purchase', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.Column('id_cart', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['book.id_book'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_cart'], ['cart.id_cart'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_purchase')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    op.drop_table('cart')
    op.drop_table('book')
    op.drop_table('client')
    op.drop_table('author')
    # ### end Alembic commands ###
